<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Actuality_admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Actuality_model');
    } 

    /*
     * Listing of actuality
     */
    function index()
    {
        $params['limit'] = 20; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('actuality/index?');
        $config['total_rows'] = $this->Actuality_model->get_all_actuality_count();
        $this->pagination->initialize($config);

        $data['actuality'] = $this->Actuality_model->get_all_actuality($params);
        
		$this->load->view('include/header');
		$this->load->view('blog/actuality/index', $data);
		$this->load->view('include/footer');
    }

    /*
     * Adding a new actuality
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('actuality_title','Actuality Title','max_length[255]|required');
		$this->form_validation->set_rules('actuality_content','Actuality Content','required');
		$this->form_validation->set_rules('actuality_picture','Actuality Picture','required');
		$this->form_validation->set_rules('category_id','Category Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'category_id' => $this->input->post('category_id'),
				'actuality_title' => $this->input->post('actuality_title'),
				'actuality_picture' => $this->input->post('actuality_picture'),
				'user_id' => '1',
				'created_at' => $this->input->post('created_at'),
				'actuality_content' => $this->input->post('actuality_content'),
            );
            
            $actuality_id = $this->Actuality_model->add_actuality($params);
            redirect('actuality_admin/index');
        }
        else
        {
			$this->load->model('Category_actuality_model');
			$data['all_category_actuality'] = $this->Category_actuality_model->get_all_category_actuality();
            
			$this->load->view('include/header');
			$this->load->view('blog/actuality/add', $data);
			$this->load->view('include/footer');
        }
    }  

    /*
     * Editing a actuality
     */
    function edit($actuality_id)
    {   
        // check if the actuality exists before trying to edit it
        $data['actuality'] = $this->Actuality_model->get_actuality($actuality_id);
        
        if(isset($data['actuality']['actuality_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('actuality_title','Actuality Title','max_length[255]|required');
			$this->form_validation->set_rules('actuality_content','Actuality Content','required');
			$this->form_validation->set_rules('actuality_picture','Actuality Picture','required');
			$this->form_validation->set_rules('category_id','Category Id','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'category_id' => $this->input->post('category_id'),
					'actuality_title' => $this->input->post('actuality_title'),
					'actuality_picture' => $this->input->post('actuality_picture'),
					'user_id' => $this->input->post('user_id'),
					'created_at' => $this->input->post('created_at'),
					'actuality_content' => $this->input->post('actuality_content'),
                );

                $this->Actuality_model->update_actuality($actuality_id,$params);            
                redirect('actuality_admin/index');
            }
            else
            {
				$this->load->model('Category_actuality_model');
				$data['all_category_actuality'] = $this->Category_actuality_model->get_all_category_actuality();

                $this->load->view('include/header');
				$this->load->view('blog/actuality/edit', $data);
				$this->load->view('include/footer');
            }
        }
        else
            show_error('The actuality you are trying to edit does not exist.');
    } 

    /*
     * Deleting actuality
     */
    function remove($actuality_id)
    {
        $actuality = $this->Actuality_model->get_actuality($actuality_id);

        // check if the actuality exists before trying to delete it
        if(isset($actuality['actuality_id']))
        {
            $this->Actuality_model->delete_actuality($actuality_id);
            redirect('actuality_admin/index');
        }
        else
            show_error('The actuality you are trying to delete does not exist.');
    }
    
}
