<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_actuality extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Category_actuality_model');
    } 

    /*
     * Listing of category_actuality
     */
    function index()
    {
        $params['limit'] = 20; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('category_actuality/index?');
        $config['total_rows'] = $this->Category_actuality_model->get_all_category_actuality_count();
        $this->pagination->initialize($config);

        $data['category_actuality'] = $this->Category_actuality_model->get_all_category_actuality($params);
  
        $this->load->view('include/header');
		$this->load->view('blog/category_actuality/index', $data);
		$this->load->view('include/footer');
    }

    /*
     * Adding a new category_actuality
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('category_name','Category Name','required|max_length[250]');
		$this->form_validation->set_rules('category_descriptionn','Category Descriptionn','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'category_name' => $this->input->post('category_name'),
				'created_at' => $this->input->post('created_at'),
				'category_descriptionn' => $this->input->post('category_descriptionn'),
            );
            
            $category_actuality_id = $this->Category_actuality_model->add_category_actuality($params);
            redirect('category_actuality/index');
        }
        else
        {
            $this->load->view('include/header');
            $this->load->view('blog/category_actuality/add');
            $this->load->view('include/footer');
        }
    }  

    /*
     * Editing a category_actuality
     */
    function edit($category_id)
    {   
        // check if the category_actuality exists before trying to edit it
        $data['category_actuality'] = $this->Category_actuality_model->get_category_actuality($category_id);
        
        if(isset($data['category_actuality']['category_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('category_name','Category Name','required|max_length[250]');
			$this->form_validation->set_rules('category_descriptionn','Category Descriptionn','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'category_name' => $this->input->post('category_name'),
					'created_at' => $this->input->post('created_at'),
					'category_descriptionn' => $this->input->post('category_descriptionn'),
                );

                $this->Category_actuality_model->update_category_actuality($category_id,$params);            
                redirect('category_actuality/index');
            }
            else
            {
                $this->load->view('include/header');
				$this->load->view('blog/category_actuality/index', $data);
				$this->load->view('include/footer');
            }
        }
        else
            show_error('The category_actuality you are trying to edit does not exist.');
    } 

    /*
     * Deleting category_actuality
     */
    function remove($category_id)
    {
        $category_actuality = $this->Category_actuality_model->get_category_actuality($category_id);

        // check if the category_actuality exists before trying to delete it
        if(isset($category_actuality['category_id']))
        {
            $this->Category_actuality_model->delete_category_actuality($category_id);
            redirect('category_actuality/index');
        }
        else
            show_error('The category_actuality you are trying to delete does not exist.');
    }
    
}
