<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index(){

		$this->load->view('include/header');
		$this->load->view('advocate/advocate/dashboard');
		$this->load->view('include/footer');

    }
}
