<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Impact extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Impact_model');
    } 

    /*
     * Listing of impact
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('impact/index?');
        $config['total_rows'] = $this->Impact_model->get_all_impact_count();
        $this->pagination->initialize($config);

        $data['impact'] = $this->Impact_model->get_all_impact($params);
        
        $this->load->view('include/header');
        $this->load->view('impact/index',$data);
        $this->load->view('include/footer');
    }

    /*
     * Adding a new impact
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('impact_titlte','Impact Titlte','required|max_length[200]');
		$this->form_validation->set_rules('impact_content','Impact Content','required');
		
		if($this->form_validation->run())     
        {   

            $config['upload_path']= './uploads/impact/';
            $config['allowed_types']= 'gif|jpg|png';
            $new_file=uniqid('blog');
            $config['file_name'] = $new_file.".jpg";

            $this->load->library('upload', $config);


            if ( ! $this->upload->do_upload('impact_picture'))
            {
                $error = array('error' => $this->upload->display_errors());
                $this->session->set_flashdata(['error'=>$error['error']]);
                redirect($_SERVER['HTTP_REFERER']);
            }
            else{

                $params = array(
                    'impact_titlte' => $this->input->post('impact_titlte'),
                    'create_at' => date('Y-m-d'),
                    'impact_picture' => '/uploads/impact/'. $config['file_name'],
                    'impact_content' => $this->input->post('impact_content'),
                );
                
                $impact_id = $this->Impact_model->add_impact($params);
                redirect('impact/index');
  
            }
            
        }
        else
        {            
           
            $this->load->view('include/header');
            $this->load->view('impact/add');
            $this->load->view('include/footer');
        }
    }  

    /*
     * Editing a impact
     */
    function edit($impact_id)
    {   
        // check if the impact exists before trying to edit it
        $data['impact'] = $this->Impact_model->get_impact($impact_id);
        
        if(isset($data['impact']['impact_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('impact_titlte','Impact Titlte','required|max_length[200]');
			$this->form_validation->set_rules('impact_content','Impact Content','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'impact_titlte' => $this->input->post('impact_titlte'),
					'create_at' => date('Y-m-d'),
					'impact_picture' => $this->input->post('impact_picture'),
					'impact_content' => $this->input->post('impact_content'),
                );

                $this->Impact_model->update_impact($impact_id,$params);            
                redirect('impact/index');
            }
            else
            {
               
                $this->load->view('include/header');
                $this->load->view('impact/edit',$data);
                $this->load->view('include/footer');
                
            }
        }
        else
            show_error('The impact you are trying to edit does not exist.');
    } 

    /*
     * Deleting impact
     */
    function remove($impact_id)
    {
        $impact = $this->Impact_model->get_impact($impact_id);

        // check if the impact exists before trying to delete it
        if(isset($impact['impact_id']))
        {
            $this->Impact_model->delete_impact($impact_id);
            redirect('impact/index');
        }
        else
            show_error('The impact you are trying to delete does not exist.');
    }
    

    function get_impacts(){

        $data['impacts'] = $this->Impact_model->get_all_impact();
        $this->load->view('Templates/header');
        $this->load->view('impact/impact',$data);
        $this->load->view('Templates/footer');

    }



    function get_detail_impact($id){
        $data['items_recents'] = $this->Impact_model->get_recent_item_impact();
        $data['impact'] = $this->Impact_model->get_impact($id);
        $this->load->view('Templates/header');
        $this->load->view('impact/impact_detail',$data);
        $this->load->view('Templates/footer');

    }
}
