<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Organisation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Organisation_model');
    } 

    /*
     * Listing of organisation
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('organisation/index?');
        $config['total_rows'] = $this->Organisation_model->get_all_organisation_count();
        $this->pagination->initialize($config);

        $data['organisation'] = $this->Organisation_model->get_all_organisation($params);

		$this->load->view('include/header');
		$this->load->view('advocate/organisation/index',$data);
		$this->load->view('include/footer');
    }

    /*
     * Adding a new organisation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_user' => $this->input->post('id_user'),
				'secteur' => $this->input->post('secteur'),
				'nom_organisation' => $this->input->post('nom_organisation'),
				'numero_enregistrement' => $this->input->post('numero_enregistrement'),
				'pays' => $this->input->post('pays'),
				'ville' => $this->input->post('ville'),
				'province' => $this->input->post('province'),
				'site_internet' => $this->input->post('site_internet'),
            );
            
            $organisation_id = $this->Organisation_model->add_organisation($params);
            redirect('organisation/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_user'] = $this->User_model->get_all_user();

			$this->load->model('Secteur_model');
			$data['all_secteur'] = $this->Secteur_model->get_all_secteur();

			$this->load->view('include/header');
			$this->load->view('advocate/organisation/add',$data);
			$this->load->view('include/footer');
        }
    }  

    /*
     * Editing a organisation
     */
    function edit($id)
    {   
        // check if the organisation exists before trying to edit it
        $data['organisation'] = $this->Organisation_model->get_organisation($id);
        
        if(isset($data['organisation']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_user' => $this->input->post('id_user'),
					'secteur' => $this->input->post('secteur'),
					'nom_organisation' => $this->input->post('nom_organisation'),
					'numero_enregistrement' => $this->input->post('numero_enregistrement'),
					'pays' => $this->input->post('pays'),
					'ville' => $this->input->post('ville'),
					'province' => $this->input->post('province'),
					'site_internet' => $this->input->post('site_internet'),
                );

                $this->Organisation_model->update_organisation($id,$params);            
                redirect('organisation/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_user'] = $this->User_model->get_all_user();

				$this->load->model('Secteur_model');
				$data['all_secteur'] = $this->Secteur_model->get_all_secteur();


				$this->load->view('include/header');
				$this->load->view('advocate/organisation/edit',$data);
				$this->load->view('include/footer');
            }
        }
        else
            show_error('The organisation you are trying to edit does not exist.');
    } 

    /*
     * Deleting organisation
     */
    function remove($id)
    {
        $organisation = $this->Organisation_model->get_organisation($id);

        // check if the organisation exists before trying to delete it
        if(isset($organisation['id']))
        {
            $this->Organisation_model->delete_organisation($id);
            redirect('organisation/index');
        }
        else
            show_error('The organisation you are trying to delete does not exist.');
    }



	function add_organisation()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'secteur' => $this->input->post('secteur'),
				'nom_organisation' => $this->input->post('nom_organisation'),
				'numero_enregistrement' => uniqid('enregistration',TRUE),
				'pays' => $this->input->post('pays'),
				'ville' => $this->input->post('ville'),
				'province' => $this->input->post('province'),
				'site_internet' => $this->input->post('site_internet'),
				'user_id'=> $this->session->userdata ('user_details')->users_id,
            );

			$this->session->set_flashdata(['success'=>true]);
            $organisation_id = $this->Organisation_model->add_organisation($params);
            redirect($_SERVER['HTTP_REFERER']);
        }
        else
        {
			$this->load->model('User_model');
			$data['all_user'] = $this->User_model->get_all_user();

			$this->load->model('Secteur_model');
			$data['all_secteur'] = $this->Secteur_model->get_all_secteur_with_object();

			$this->load->view('include/header');
			$this->load->view('advocate/organisation/organisation_form',$data);
			$this->load->view('include/footer');
        }
    }  
    
}
