<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Storie extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Storie_model');
    } 

    /*
     * Listing of storie
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('storie/index?');
        $config['total_rows'] = $this->Storie_model->get_all_storie_count();
        $this->pagination->initialize($config);

        $data['storie'] = $this->Storie_model->get_all_storie($params);
        $this->load->view('include/header');
        $this->load->view('storie/index',$data);
        $this->load->view('include/footer');
    }

    /*
     * Adding a new storie
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('storie_title','Storie Title','required|max_length[200]');
		$this->form_validation->set_rules('storie_content','Storie Content','required');
		
		if($this->form_validation->run())     
        {   
            $config['upload_path']= './uploads/storie/';
            $config['allowed_types']= 'gif|jpg|png';
            $new_file=uniqid('storie');
            $config['file_name'] = $new_file.".jpg";

            $this->load->library('upload', $config);


            if ( ! $this->upload->do_upload('storie_picture'))
            {
                $error = array('error' => $this->upload->display_errors());
                $this->session->set_flashdata(['error'=>$error['error']]);
                redirect($_SERVER['HTTP_REFERER']);
            }
            else{

                $params = array(
                    'storie_title' => $this->input->post('storie_title'),
                    'create_at' => date('Y-m-d'),
                    'storie_picture' => '/uploads/storie/'. $config['file_name'],
                    'storie_content' => $this->input->post('storie_content'),
                );
                
                $storie_id = $this->Storie_model->add_storie($params);
                redirect('storie/index');
  
            }

            
        }
        else
        {   
            $this->load->view('include/header');
            $this->load->view('storie/add');
            $this->load->view('include/footer');
        }
    }  

    /*
     * Editing a storie
     */
    function edit($storie_id)
    {   
        // check if the storie exists before trying to edit it
        $data['storie'] = $this->Storie_model->get_storie($storie_id);
        
        if(isset($data['storie']['storie_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('storie_title','Storie Title','required|max_length[200]');
			$this->form_validation->set_rules('storie_content','Storie Content','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'storie_title' => $this->input->post('storie_title'),
					'create_at' => date('Y-m-d'),
					'storie_picture' => $this->input->post('storie_picture'),
					'storie_content' => $this->input->post('storie_content'),
                );

                $this->Storie_model->update_storie($storie_id,$params);            
                redirect('storie/index');
            }
            else
            {
                $this->load->view('include/header');
                $this->load->view('storie/edit',$data);
                $this->load->view('include/footer');
            }
        }
        else
            show_error('The storie you are trying to edit does not exist.');
    } 

    /*
     * Deleting storie
     */
    function remove($storie_id)
    {
        $storie = $this->Storie_model->get_storie($storie_id);

        // check if the storie exists before trying to delete it
        if(isset($storie['storie_id']))
        {
            $this->Storie_model->delete_storie($storie_id);
            redirect('storie/index');
        }
        else
            show_error('The storie you are trying to delete does not exist.');
    }



    function get_stories(){

        $data['stories'] = $this->Storie_model->get_all_storie();
        $this->load->view('Templates/header');
        $this->load->view('storie/storie',$data);
        $this->load->view('Templates/footer');

    }



    function get_detail_storie($id){

        $data['storie'] = $this->Storie_model->get_storie($id);
		
        $this->load->view('Templates/header');
        $this->load->view('storie/storie_detail',$data);
        $this->load->view('Templates/footer');

    }
    
}
