<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categorie_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categorie_user by id
     */
    function get_categorie_user($id)
    {
        return $this->db->get_where('categorie_user',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all categorie_user count
     */
    function get_all_categorie_user_count()
    {
        $this->db->from('categorie_user');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all categorie_user
     */
    function get_all_categorie_user($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('categorie_user')->result_array();
    }
        
    /*
     * function to add new categorie_user
     */
    function add_categorie_user($params)
    {
        $this->db->insert('categorie_user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categorie_user
     */
    function update_categorie_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('categorie_user',$params);
    }
    
    /*
     * function to delete categorie_user
     */
    function delete_categorie_user($id)
    {
        return $this->db->delete('categorie_user',array('id'=>$id));
    }
}
