<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_blog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category_blog by category_id
     */
    function get_category_blog($category_id)
    {
        return $this->db->get_where('category_blog',array('category_id'=>$category_id))->row_array();
    }
    
    /*
     * Get all category_blog count
     */
    function get_all_category_blog_count()
    {
        $this->db->from('category_blog');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all category_blog
     */
    function get_all_category_blog($params = array())
    {
        $this->db->order_by('category_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('category_blog')->result_array();
    }
        
    /*
     * function to add new category_blog
     */
    function add_category_blog($params)
    {
        $this->db->insert('category_blog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category_blog
     */
    function update_category_blog($category_id,$params)
    {
        $this->db->where('category_id',$category_id);
        return $this->db->update('category_blog',$params);
    }
    
    /*
     * function to delete category_blog
     */
    function delete_category_blog($category_id)
    {
        return $this->db->delete('category_blog',array('category_id'=>$category_id));
    }


	function get_all_cateogry_with_object(){

		return $this->db->get('category_blog')->result();
	}
}
