<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_actuality_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category_actuality by category_id
     */
    function get_category_actuality($category_id)
    {
        return $this->db->get_where('category_actuality',array('category_id'=>$category_id))->row_array();
    }
    
    /*
     * Get all category_actuality count
     */
    function get_all_category_actuality_count()
    {
        $this->db->from('category_actuality');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all category_actuality
     */
    function get_all_category_actuality($params = array())
    {
        $this->db->order_by('category_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('category_actuality')->result_array();
    }
        
    /*
     * function to add new category_actuality
     */
    function add_category_actuality($params)
    {
        $this->db->insert('category_actuality',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category_actuality
     */
    function update_category_actuality($category_id,$params)
    {
        $this->db->where('category_id',$category_id);
        return $this->db->update('category_actuality',$params);
    }
    
    /*
     * function to delete category_actuality
     */
    function delete_category_actuality($category_id)
    {
        return $this->db->delete('category_actuality',array('category_id'=>$category_id));
    }
}
