<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comment by comment_id
     */
    function get_comment($comment_id)
    {
        return $this->db->get_where('comment',array('comment_id'=>$comment_id))->row_array();
    }
    
    /*
     * Get all comment count
     */
    function get_all_comment_count()
    {
        $this->db->from('comment');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all comment
     */
    function get_all_comment($params = array())
    {
        $this->db->order_by('comment_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('comment')->result_array();
    }
        
    /*
     * function to add new comment
     */
    function add_comment($params)
    {
        $this->db->insert('comment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comment
     */
    function update_comment($comment_id,$params)
    {
        $this->db->where('comment_id',$comment_id);
        return $this->db->update('comment',$params);
    }
    
    /*
     * function to delete comment
     */
    function delete_comment($comment_id)
    {
        return $this->db->delete('comment',array('comment_id'=>$comment_id));
    }


	function get_comment_of_item_blog($item_id){

		return $this->db->get_where('comment',array('comment_item_id'=>$item_id))->result();
	}


	function count_comment_of_item_blog($item_id){

		$this->db->from('comment');
		$this->db->where(['comment_item_id'=>$item_id]);
		return $this->db->count_all_results();
	}

}
