<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commission_groupe_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commission_groupe by id
     */
    function get_commission_groupe($id)
    {
        return $this->db->get_where('commission_groupe',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all commission_groupe count
     */
    function get_all_commission_groupe_count()
    {
        $this->db->from('commission_groupe');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all commission_groupe
     */
    function get_all_commission_groupe($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('commission_groupe')->result_array();
    }
        
    /*
     * function to add new commission_groupe
     */
    function add_commission_groupe($params)
    {
        $this->db->insert('commission_groupe',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commission_groupe
     */
    function update_commission_groupe($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('commission_groupe',$params);
    }
    
    /*
     * function to delete commission_groupe
     */
    function delete_commission_groupe($id)
    {
        return $this->db->delete('commission_groupe',array('id'=>$id));
    }
}
