<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commission_tech_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commission_tech by id
     */
    function get_commission_tech($id)
    {
        return $this->db->get_where('commission_tech',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all commission_tech count
     */
    function get_all_commission_tech_count()
    {
        $this->db->from('commission_tech');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all commission_tech
     */
    function get_all_commission_tech($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('commission_tech')->result_array();
    }
        
    /*
     * function to add new commission_tech
     */
    function add_commission_tech($params)
    {
        $this->db->insert('commission_tech',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commission_tech
     */
    function update_commission_tech($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('commission_tech',$params);
    }
    
    /*
     * function to delete commission_tech
     */
    function delete_commission_tech($id)
    {
        return $this->db->delete('commission_tech',array('id'=>$id));
    }
}
