<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupe_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get groupe_user by id
     */
    function get_groupe_user($id)
    {
        return $this->db->get_where('groupe_user',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all groupe_user count
     */
    function get_all_groupe_user_count()
    {
        $this->db->from('groupe_user');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all groupe_user
     */
    function get_all_groupe_user($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('groupe_user')->result_array();
    }
        
    /*
     * function to add new groupe_user
     */
    function add_groupe_user($params)
    {
        $this->db->insert('groupe_user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update groupe_user
     */
    function update_groupe_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('groupe_user',$params);
    }
    
    /*
     * function to delete groupe_user
     */
    function delete_groupe_user($id)
    {
        return $this->db->delete('groupe_user',array('id'=>$id));
    }

    function getListUserForgroupUser($groupe_user_id){

        $this->db->join('users', 'users.users_id = groupe_user.id_user');
        $this->db->join('goupe', 'goupe.id = groupe_user.id_group');

        return $this->db->get_where('groupe_user', array('groupe_user.id' => $groupe_user_id))->result();
    }
}
