<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Impact_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get impact by impact_id
     */
    function get_impact($impact_id)
    {
        return $this->db->get_where('impact',array('impact_id'=>$impact_id))->row_array();
    }
    
    /*
     * Get all impact count
     */
    function get_all_impact_count()
    {
        $this->db->from('impact');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all impact
     */
    function get_all_impact($params = array())
    {
        $this->db->order_by('impact_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('impact')->result_array();
    }
        
    /*
     * function to add new impact
     */
    function add_impact($params)
    {
        $this->db->insert('impact',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update impact
     */
    function update_impact($impact_id,$params)
    {
        $this->db->where('impact_id',$impact_id);
        return $this->db->update('impact',$params);
    }
    
    /*
     * function to delete impact
     */
    function delete_impact($impact_id)
    {
        return $this->db->delete('impact',array('impact_id'=>$impact_id));
    }


    function get_recent_item_impact(){

		$this->db->order_by('impact_id', 'desc');
		$this->db->limit(6,0);
		return $this->db->get('impact')->result();
	}
}
