<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_blog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item_blog by item_id
     */
    function get_item_blog($item_id)
    {
        return $this->db->get_where('item_blog',array('item_id'=>$item_id))->row_array();
    }
    
    /*
     * Get all item_blog count
     */
    function get_all_item_blog_count()
    {
        $this->db->from('item_blog');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all item_blog
     */
    function get_all_item_blog($params = array())
    {
        $this->db->order_by('item_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('item_blog')->result_array();
    }

	function get_all_item_blog_with_object(){

    	$this->db->join('category_blog','category_blog.category_id = item_blog.item_category_id');
		return $this->db->get('item_blog')->result();
	}
        
    /*
     * function to add new item_blog
     */
    function add_item_blog($params)
    {
        $this->db->insert('item_blog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item_blog
     */
    function update_item_blog($item_id,$params)
    {
        $this->db->where('item_id',$item_id);
        return $this->db->update('item_blog',$params);
    }
    
    /*
     * function to delete item_blog
     */
    function delete_item_blog($item_id)
    {
        return $this->db->delete('item_blog',array('item_id'=>$item_id));
    }


    function item_blog_by_id($item_id){

        return $this->db->get_where('item_blog',array('item_id'=>$item_id))->result();
    }

	function get_recent_item_blog(){

		$this->db->order_by('item_id', 'desc');
		$this->db->limit(6,0);
		return $this->db->get('item_blog')->result();
	}


	function get_all_item_by_category($category_id){
		$this->db->join('category_blog','category_blog.category_id = item_blog.item_category_id');
		return $this->db->get_where('item_blog',array('item_category_id'=>$category_id))->result();
	}
}
