<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Organisation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get organisation by id
     */
    function get_organisation($id)
    {
        return $this->db->get_where('organisation',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all organisation count
     */
    function get_all_organisation_count()
    {
        $this->db->from('organisation');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all organisation
     */
    function get_all_organisation($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('organisation')->result_array();
    }


	function get_organisation_object($id){

		$this->db->where(['user_id'=>$id]);
		return $this->db->get('organisation')->result();
	}
        
    /*
     * function to add new organisation
     */
    function add_organisation($params)
    {
        $this->db->insert('organisation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update organisation
     */
    function update_organisation($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('organisation',$params);
    }
    
    /*
     * function to delete organisation
     */
    function delete_organisation($id)
    {
        return $this->db->delete('organisation',array('id'=>$id));
    }
}
