<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get secteur by id
     */
    function get_role($id)
    {
        return $this->db->get_where('user_role',array('user_role_id'=>$id))->row_array();
    }
    
    /*
     * Get all secteur count
     */
    function get_all_role_count()
    {
    	$this->db->from("user_role");
        return $this->db->count_all_results();
    }
        
    /*
     * Get all secteur
     */
    function get_all_role($params = array())
    {
        $this->db->order_by('user_role_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('user_role')->result();
    }


	function get_all_ressource_with_object()
    {
    
        return $this->db->get('user_role')->result();
    }
	
        
    /*
     * function to add new secteur
     */
    function add_role($params)
    {
        $this->db->insert('user_role',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update secteur
     */
    function update_role($id,$params)
    {
        $this->db->where('user_role_id',$id);
        return $this->db->update('user_role',$params);
    }
    
    /*
     * function to delete secteur
     */
    function delete_role($id)
    {
        return $this->db->delete('user_role',array('user_role_id'=>$id));
    }
}
