<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Secteur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get secteur by id
     */
    function get_secteur($id)
    {
        return $this->db->get_where('secteur',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all secteur count
     */
    function get_all_secteur_count()
    {
    	$this->db->from("secteur");
        return $this->db->count_all_results();
    }
        
    /*
     * Get all secteur
     */
    function get_all_secteur($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('secteur')->result_array();
    }


	function get_all_secteur_with_object()
    {
    
        return $this->db->get('secteur')->result();
    }
	
        
    /*
     * function to add new secteur
     */
    function add_secteur($params)
    {
        $this->db->insert('secteur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update secteur
     */
    function update_secteur($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('secteur',$params);
    }
    
    /*
     * function to delete secteur
     */
    function delete_secteur($id)
    {
        return $this->db->delete('secteur',array('id'=>$id));
    }
}
