<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Storie_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get storie by storie_id
     */
    function get_storie($storie_id)
    {
        return $this->db->get_where('storie',array('storie_id'=>$storie_id))->row_array();
    }
    
    /*
     * Get all storie count
     */
    function get_all_storie_count()
    {
        $this->db->from('storie');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all storie
     */
    function get_all_storie($params = array())
    {
        $this->db->order_by('storie_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('storie')->result_array();
    }
        
    /*
     * function to add new storie
     */
    function add_storie($params)
    {
        $this->db->insert('storie',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update storie
     */
    function update_storie($storie_id,$params)
    {
        $this->db->where('storie_id',$storie_id);
        return $this->db->update('storie',$params);
    }
    
    /*
     * function to delete storie
     */
    function delete_storie($storie_id)
    {
        return $this->db->delete('storie',array('storie_id'=>$storie_id));
    }
}
