<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class View_blog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get view_blog by view_id
     */
    function get_view_blog($view_id)
    {
        return $this->db->get_where('view_blog',array('view_id'=>$view_id))->row_array();
    }
        
    /*
     * Get all view_blog
     */
    function get_all_view_blog()
    {
        $this->db->order_by('view_id', 'desc');
        return $this->db->get('view_blog')->result_array();
    }
        
    /*
     * function to add new view_blog
     */
    function add_view_blog($params)
    {
        $this->db->insert('view_blog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update view_blog
     */
    function update_view_blog($view_id,$params)
    {
        $this->db->where('view_id',$view_id);
        return $this->db->update('view_blog',$params);
    }
    
    /*
     * function to delete view_blog
     */
    function delete_view_blog($view_id)
    {
        return $this->db->delete('view_blog',array('view_id'=>$view_id));
    }
}
